version: '2'
services:
  web:
    image: httpd
    ports:
      - "81:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  fluentd:
    build: ./
    volumes:
      - ./dev/fluent.conf:/fluentd/etc/fluent.conf
      - ./:/plugins
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    tty: true
    command: ["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c","/fluentd/etc/fluent.conf"]
