version: '2'
services:
  web:
    image: httpd
    ports:
      - "81:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
  fluentd:
    build: ./
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ../:/plugin
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    tty: true
    command: ["sh"]
